name: icc_apps
services:
  covoiturage:
      #image: iccbrx/covoiturage:latest
      build: 
        context: ./
      container_name: covoiturage
      networks:
        covoiturage_net:
          ipv4_address: ${COVOITURAGE_IP}
      ports:
      - "3022:3000"

networks:
  covoiturage_net:
    ipam:
      driver: default
      config:
          - 
            subnet: ${COVOITURAGE_NETWORK}