name: icc_apps

services:
  covoiturage:
    build:
      context: ./
      args:
        - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
        - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
        - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
        - NEXT_PUBLIC_FIREBASE_VAPID_KEY=${NEXT_PUBLIC_FIREBASE_VAPID_KEY}
    container_name: covoiturage
    networks:
      covoiturage_net:
        ipv4_address: ${COVOITURAGE_IP}
    ports:
      - "3022:3000"

networks:
  covoiturage_net:
    ipam:
      driver: default
      config:
        - subnet: ${COVOITURAGE_NETWORK}
# name: icc_apps

# services:
#   covoiturage:
#     build: 
#       context: ./
#       args:
#         - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
#         - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
#         - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
#         - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
#         - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
#         - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
#         - NEXT_PUBLIC_FIREBASE_VAPID_KEY=${NEXT_PUBLIC_FIREBASE_VAPID_KEY}
#         - NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL=${NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL}
#         - NEXT_PUBLIC_FIREBASE_PRIVATE_KEY=${NEXT_PUBLIC_FIREBASE_PRIVATE_KEY}
#     container_name: covoiturage
#     networks:
#       covoiturage_net:
#         ipv4_address: ${COVOITURAGE_IP}
#     ports:
#       - "3022:3000"
#     environment:
#       - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
#       - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
#       - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
#       - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
#       - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
#       - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
#       - NEXT_PUBLIC_FIREBASE_VAPID_KEY=${NEXT_PUBLIC_FIREBASE_VAPID_KEY}
#       - NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL=${NEXT_PUBLIC_FIREBASE_CLIENT_EMAIL}
#       - NEXT_PUBLIC_FIREBASE_PRIVATE_KEY=${NEXT_PUBLIC_FIREBASE_PRIVATE_KEY}

# networks:
#   covoiturage_net:
#     ipam:
#       driver: default
#       config:
#         - subnet: ${COVOITURAGE_NETWORK}
